### ISSUE TITLE
Get BibTeX data programmatically?

### ISSUE THREAD

**Issue by davclark** [CrossRef/rest-api-doc#115]
I'm trying to figure out if I can get the BibTeX data once I find a record (I can find the DOI easily, and also the JSON data for a record). The BibTeX comes up in the Articles drop-down, which is triggering the showCiteBox function, but it hits a `citation-text` element which I guess is also programmatically populated?

My javascript ain't great. So, help figuring out how to get the data that goes in `citation-text` would be awesome.

cc @YangZhou0417 @zongjinglin

**Comment by sckott** [comment]
maybe you're looking for http://www.crosscite.org/cn/

**Comment by davclark** [comment]
Indeed, I think so! Are there docs that I didn't read that would've led me to this page?

**Comment by sckott** [comment]
dont know - i don't think use of this API for content negotiation is documented in their docs :(

**Comment by kjw** [comment]
Right, there is an undocumented feature of the API where content negotiated DOI requests can be served with the `transform` routes:

    http://api.crossref.org/works/10.5555/12345678/transform/application/x-bibtex

In the past I've decided to leave it undocumented because it misses the point of the implementation of content negotiation on DOIs: that it works across DOI registration agencies, especially Crossref, DataCite, mEDRA and ChinaDOI. Also these path-based content selection routes don't support content negotiation parameters, so for example there is no equivalent of:

    curl -iH "Accept: text/x-bibliography; style=apa; locale=fr-FR" http://doi.org/10.5555/12345678

But if people would find it useful to have basic path based selection of the metadata representation format, then maybe I should document it.

**Comment by Watterry** [comment]
I think the API to return BibTeX will be useful. In particular, it would be nice to be able to rely only on the title of the paper and not have to use a DOI to return it.
