### ISSUE TITLE
Article references journal that doesn't exist in DB

### ISSUE THREAD

**Issue by unoexperto** [CrossRef/rest-api-doc#139]
Found an article http://api.crossref.org/works/10.5812/thrita.7384 that references journal that doesn't exist in DB.

Is this a bug or should I expect same often ?

Interestingly enough lookup by these two ISSNs in NCBI's NLM Catalog locates journal but it doesn't have given ISSNs either.

http://www.ncbi.nlm.nih.gov/nlmcatalog?term=2322-2689%5BISSN%5D

Weird.

What do you guys think ?

**Comment by kjw** [comment]
I need to investigate what happens during deposit of metadata. Our main system outputs journals registered with us and this is what I use to construct a list of ISSNs within the API for /journals. It is possible that deposit of work metadata allows ISSNs that are not in that list. Or it could be that the list I receive is incomplete due to some bug somewhere. Will let you know when I can say how we will fix this.

**Comment by cppexpert** [comment]
Thanks!. In my analysis there are ~2K ISSNs in CrossRef works DB that don't have matching journals. I matched some of the with DB from WorldCat but it's incomplete as well.

**Comment by gbilder** [comment]
This is, indeed, very odd. This DOI entry:

http://api.crossref.org/works/10.5812/thrita.7384

lists these two ISSNs:

-` 2322-2689`
- `2322-2697`

Neither of which seem to even exist in *our* API database:

- `http://api.crossref.org/journals/2322-2689`
- `http://api.crossref.org/journals/2322-2697`

Or in our title list:

https://www.crossref.org/titleList/

But if you look them up at NCBI, you get a record for the correct journal. But the ISSNs listed there are entirely different:

- `https://www.ncbi.nlm.nih.gov/nlmcatalog?term=2322-2689%5BISSN%5D`
- `https://www.ncbi.nlm.nih.gov/nlmcatalog?term=2322-2697%5BISSN%5D`

NCBI record lists:

- 2352-0612 (Print)
- 2352-0620 (Electronic)
- 2352-0612 (Linking)

And if you take the ISSNs that are listed in NCBI, and look them up on Crossref, you find we have the correct records for them:

- http://api.crossref.org/journals/2352-0612
- http://api.crossref.org/journals/2352-0620

And they are listed in our title list:

- https://www.crossref.org/titleList/

This makes my brain hurt.

I *suspect* that what is happening is:

* We require an ISSN for deposit
* If an ISSN changes because of a title change, we do not maintain the connection between the old ISSN and the new ISSN in our journal record. But NCBI does.
* The old record keeps the old ISSN (as it should).
* Our ISSN title list only had the current ISSN.

If this is true, then what this means is that:

- API queries on ISSNs where there has been a title change, will not show records prior to the title change. This seems to be correct behaviour.
- But-- we don't have any way of listing anything other than current ISSNs, so there is not even a way to go get works associated with an old ISSN if somebody happens to have it.

A way to fix this would be either:

1) To miraculously discover that we keep history of ISSN name changes and include those in both the title list and the API.
2) for the API to not rely on our title list as its canonical source for data about what is in our database.

**Comment by unoexperto** [comment]
@gbilder In my database I merge such journals. Thus record has the latest title and all ISSNs. I know it's not perfect solution but unless somebody requests historic information I'm not planning to keep history of changes. Also article record contains both my internal journal ID and ISSN I've got from you (or other content provider).

**Comment by kjw** [comment]
Same as #247

**Comment by kjw** [comment]
@ckoscher These ISSNs:

- `2322-2689`
- `2322-2697`

are *not* listed in the `titleFile.csv` file.

**Comment by jenniferlin15** [comment]
Ticketed - CS-3596
