### ISSUE TITLE
prefixes route returning records with different prefix

### ISSUE THREAD

**Issue by mark-donoghue** [CrossRef/rest-api-doc#148]
Example:
http://api.crossref.org/prefixes/10.1109/works?rows=100&cursor=*

Has in the results a record for the following DOI:
"http://dx.doi.org/10.1002/1538-7035(199622)1:1%3C100::aid-bltj2007%3E3.0.co;2-n"

_Yes, the DOI has angle brackets._

The prefix belongs to IEEE and the DOI with the 10.1002 prefix was registered by IEEE.

Was expecting records with DOIs having only the 10.1109 prefix.

**Comment by kjw** [comment]
This is actually expected behaviour, the /prefixes routes returns DOIs associated with a particular 'owner prefix' (in this case 10.1109). You can see more clearly in the UNIXSD XML for the record that the owner prefix is `10.1109`:

http://doi.crossref.org/openurl?noredirect=true&pid=kward@crossref.org&id=doi:10.1002/1538-7035(199622)1:1%3C100::aid-bltj2007%3E3.0.co;2-n&format=unixsd

Owner prefix may differ from literal prefix found in the DOI after a journal transfer or other event that may change the owning publisher (for want of better terminology) of content.
