### ISSUE TITLE
Authors missing

### ISSUE THREAD

**Issue by Daniel-Mietchen** [CrossRef/rest-api-doc#157]
In
https://api.crossref.org/v1/works/http://dx.doi.org/10.1001/archophthalmol.2010.159 ,
only the first author of
http://dx.doi.org/10.1001/archophthalmol.2010.159
is indicated.

**Comment by ioverka** [comment]
This seems to be due to the publisher only pushing the first author to CrossRef. The UNIXREF format of the same DOI doesn't include any additional information, see
http://www.crossref.org/openurl?pid=YOURMAIL&id=doi:10.1001/archophthalmol.2010.159&redirect=false&format=unixref - so you probably should talk to the AMA?

BTW: Is it guaranteed/documented that a DOI resolver URL qualifies as input for the CrossRef DOI? I was actually surprised that this is working...

**Comment by ioverka** [comment]
ah... another trick to receive the full deposited XML is to add .xml to the API request, see https://api.crossref.org/v1/works/http://dx.doi.org/10.1001/archophthalmol.2010.159.xml
