### ISSUE TITLE
Journals with ISSN 0000-0000

### ISSUE THREAD

**Issue by hubgit** [CrossRef/rest-api-doc#160]
There are many journals with "0000-0000" as an ISSN - [here's one example](https://api.crossref.org/journals/0033-0337). 

This ISSN should probably be filtered out?

There are also [many works associated with this ISSN](https://api.crossref.org/works?filter=issn:0000-0000).

**Comment by ioverka** [comment]
Wow, 60373 records - that is a lot! According to my understanding ISSN 0000-0000 has sometimes been used as "dummy" ISSN by publishers, see http://www.crossref.org/10meetings/Technical_Patricia_Feeney.pdf

So, the issue is known, but it's pobably very difficult for CrossRef to cleanup all their data... so I guess filtering is a good idea ;)
