### ISSUE TITLE
Error when using filter and rows params together

### ISSUE THREAD

**Issue by sckott** [CrossRef/rest-api-doc#171]
this used to work https://api.crossref.org/works?rows=0&facet=license%3A%2A&filter=has-full-text%3Atrue

but now returns

```json
{
    "status": "error",
    "message-type": "exception",
    "message-version": "1.0.0",
    "message": {
        "name": "class java.lang.RuntimeException",
        "description": "java.lang.RuntimeException: Solr returned a partial result set",
        "message": "Solr returned a partial result set",
        "cause": null
    }
}
```

works if i don't include the `rows` param, but of course when filtering one often wants to speed up return result, so limiting rows=0 is important

**Comment by sckott** [comment]
same exception on this request http://api.crossref.org/works?order=asc&query=ecology&sort=indexed

**Comment by sckott** [comment]
this is also failing now 

http://api.crossref.org/works?filter=has-full-text:true

```json
{
  "status": "error",
  "message-type": "exception",
  "message-version": "1.0.0",
  "message": {
    "name": "class java.lang.RuntimeException",
    "description": "java.lang.RuntimeException: Solr returned a partial result set",
    "message": "Solr returned a partial result set",
    "cause": null
  }
}
```

**Comment by sckott** [comment]
Anything change with respect to filters?

**Comment by sckott** [comment]
Getting these `Solr returned a partial result set` errors at lot now

**Comment by jbborre** [comment]
We are also receiving quite a few Solr errors thru the Crossref API.

**Comment by kjw** [comment]
These are coming back as a result of imposing a time limit on solr queries. We just upped that time limit from 5s to 30s. I'd appreciate it if you let me know if you've noticed different behaviour since yesterday when we increased the time limit. 

We had to impose a time limit to keep the system running - many long running queries were killing our solr servers.

I'm considering a flag that will let users specify that the query should run without a time limit. In this case we'd pass the queries onto a separate set of servers that don't time out queries, but that may take a while to respond.

**Comment by jbborre** [comment]
Hey Karl,

Thanks for the response!  I have not seen any errors returned back from
solr since you increased the timeout.  Just a couple recommendations:  I
would catch the solr exception and re-throw as your own timeout exception
or custom exception without stack trace, maybe even simply the timeout http
status code.  By allowing your technology specific exceptions bubble up,
you could be exposing more than you want. To protect your own solr instance
from long running queries, you probably still want a timeout of some sort
but I dont think you should expose that.  If a client cares about timing
out their own request they can and should know how to do so.  I use spring
restTemplate which allows setting a timeout pretty easily.  You might be
better off catching a timeout and throwing an exception explaining that the
search needs to be revised so that results could be returned.  That's my 2
cents.  Thanks for the help!

Jonathan

**Comment by sckott** [comment]
Thanks for explanation.   Still getting the same errors in some cases

**Comment by jbborre** [comment]
FYI, we are seeing periodic solr errors again.

Thanks
Jonathan

On Tue, Jan 10, 2017 at 1:06 PM, Scott Chamberlain <notifications@github.com

**Comment by Aeolun** [comment]
@kjw Anything you can do about this? The errors occur on pretty much any query we run on the service now. I have to re-run every query a few times to finally see it succeeding, undoubtedly putting even more load on the system.

**Comment by kmeddings** [comment]
We recently added new fields to the API (references being the main one - which is a lot of additional metadata) and this has resulted in a much bigger index. We have a dedicated team working on it this week to stabilise and improve performance. Fixes put in today should  have helped. Thanks for being patient - can you let us know if you are seeing any improvement?

**Comment by sckott** [comment]
Just ran test suite a few times on some of my clients, and still get same error as above on some http requests (doesn't error every time, same as before)  - will test again soon

**Comment by kjw** [comment]
I'm trying to get the timeouts removed, as I don't think they help with system load anyway.

**Comment by kjw** [comment]
We've increased the maximum time allowed for queries, but if this continues, please reopen.
