### ISSUE TITLE
Clarification of API rate limits

### ISSUE THREAD

**Issue by unoexperto** [CrossRef/rest-api-doc#196]
Guys, could you please clarify meaning of rate limiting headers ? For example I see this now

```
X-Rate-Limit-Interval →1s
X-Rate-Limit-Limit →50
```

Does it mean 50 calls per second ? If yes it doesn't seem to work for me. My calls appear to be throttled.

This call, for example, never returns any data but connection is established

http://api.crossref.org/works?rows=1000&filter=type:journal-article&order=asc&sort=deposited&cursor=AoJ4%2B%2B6YzaYCPwxodHRwOi8vZHguZG9pLm9yZy8xMC4xMDE3L3MwMTQwNTI1eDAwMDE5NjQ2

As alternative would it be possible to download current snapshot in json in bulk ?

Thank you!

**Comment by unoexperto** [comment]
@kmeddings Could you please advice what to do ? Thanks!!

**Comment by gbilder** [comment]
The rate limit is as you read it- that means 50 queries per second. If you are experiencing timeouts, it could be due to a sharp increase in overall load that we've recently experienced. We are in the process of refactoring the API code and upgrading equipment to deal with it. Having said that, when I try your query I am getting an error related to the filter combination. Am reassigning this.

**Comment by kmeddings** [comment]
The above query is now working.
