### ISSUE TITLE
Missing License Information for Many Articles

### ISSUE THREAD

**Issue by moqri** [CrossRef/rest-api-doc#258]
It seem a large portion of the articles in CrossRef are missing the license information (93% based on this new study https://peerj.com/preprints/3119v1/). Is there a specific reason behind it? Any workaround to get this information?

**Comment by moqri** [comment]
It seems it is better for more recent years, but still most of the articles do not have this information. Example 65% of articles published in 2013 are missing license information

**Comment by kjw** [comment]
Pretty much all Crossref metadata is optional. Publishers deposit what they do, in some cases they may not deposit a particular piece of information because their systems have not been updated to do so, or because they don't collect it, or know it, or because they don't want to share the information.

We always make the case for our members to deposit as much information as possible. Coverage is generally better for more recently published content.
