### ISSUE TITLE
Route not found for many journals

### ISSUE THREAD

**Issue by kaltri-n** [CrossRef/rest-api-doc#349]
Hi, 

I have a large list of ISSNs that I need metadata (like DOIs, title, authors etc) for my research. For some ISSNs I retrieved the metadata but for some not. I get a message: "Route not found". 
Could you please let me know what to do?
Thanks in advance for your help on this.
Kaltri

**Comment by pdavis8** [comment]
Hello Kaltri, 
Could you post some of ISSNs that returned the error message and I will check them here for you.
Thanks,
Paul

**Comment by kaltri-n** [comment]
Hi Paul,
here are some ISSNs that returned the error message: 0002-1121, 0013-0419, 0001-8376, 1574-0862, 0028-0453, 0098-9495. 
thanks,
Kaltri

**Comment by pdavis8** [comment]
Hello Kaltri,

Thanks for sending over that information, I have had a quick look on our system here and all but one of those ISSNs has not been registered with us yet. This is probably why the results are being returned 'null'.
This is the only ISSN (1574-0862) that is showing in our system so that one should really work fine, it is showing up from this query: http://api.crossref.org/journals/1574-0862
I would guess that the other ~500 would probably not be registered with us yet.

I hope this helps.

Thanks,
Paul

**Comment by kaltri-n** [comment]
Hi Paul, 
thank you. 
Since I need the data for my PhD and want them to be complete, do you mind if I send you my ISSNs that return that error message, and you might want to have a look for them?
