### ISSUE TITLE
No data for some DOIs from OUP

### ISSUE THREAD

**Issue by danielopitz** [CrossRef/rest-api-doc#403]
I have found examples for Oxford University Press metadata missing for DOIs advertised on their pages:

http://internationalstudies.oxfordre.com/view/10.1093/acrefore/9780190846626.001.0001/acrefore-9780190846626-e-120 advertises 10.1093/acrefore/9780190846626.013.120 as the article's DOI, but 
https://api.crossref.org/works/10.1093/acrefore/9780190846626.013.120 shows resource not found.

This is the case for rather a big chunk of Oxford Research Encyclopedia collection. Additionally, the articles are indexed as books, which is confusing. I'd have thought, that these are book chapters.

**Comment by pdavis8** [comment]
Hello,

Thanks for your attention on this. If you try to resolve a DOI here https://doi.org/ then if it is not found it will bring up a form what you can fill in to alert the publisher that the DOI is not resolving and you can also add an email address in so that you are notified when this DOI is registered.
I can also send this information onto Oxford University Press if you would like me to, please do send over a list of DOIs that are not resolving but showing as published and I will forward them on.

Thanks,
