### ISSUE TITLE
filter=from-pub-date brings out wrong results

### ISSUE THREAD

**Issue by anmipac** [CrossRef/rest-api-doc#425]
Hello, thank you for the excellent service with the CrossRef REST API!

I noticed a weird behaviour regarding this:
https://api.crossref.org/journals/1464-3596/works?sort=issued&order=desc&filter=from-pub-date:2018-02

Note that I filter the journal's works from Feb. 2018 using "**from-pub-date:2018-02**".

However, the first result was:
- "indexed" in 2018-10-30
- "published-print" in 2018-07-23
- "created" in 2018-05-30
- "published-online" in 2018-07-23
- "deposited" in 2018-07-23
- "issued" in 2018-05

etc., while nothing points to Feb. 2018! The same is actually true for other items.

I would expect that result to be found when I use the filter "**from-pub-date:2018-07**" (July 2018). However, [using this filter](https://api.crossref.org/journals/1464-3596/works?sort=issued&order=desc&filter=from-pub-date:2018-07) yields 0 results.

How is that possible? Is there an error or did I misunderstand something?

I would be grateful for your help. Thank you!

**Comment by pdavis8** [comment]
Hello,
Thanks for the query. 

I created a new call for the API below and I could not work out why this was still showing the DOIs even though neither online or print publication date were from February:
https://api.crossref.org/journals/1464-3596/works?filter=from-pub-date:2018-02-01,until-pub-date:2018-02-28&sort=issued&order=desc&select=DOI,published-print,published-online
Then I looked into the DOIs that were being returned and I can see that there is another "other" publication date which does say February.
http://api.crossref.org/works/10.1093/ejil/chy009/transform/application/vnd.crossref.unixsd+xml
The other filter will be returning 0 results because there has been nothing published after that date I believe.
