### ISSUE TITLE
until-created-date

### ISSUE THREAD

**Issue by anmipac** [CrossRef/rest-api-doc#429]
Hello,
my attempt at using the filter "**until-created-date**" does not work:

https://api.crossref.org/journals/1460-3667/works?sort=issued&order=desc&filter=from-created-date:2018-11-01&until-created-date:2018-11-30

Error:

> {"status":"failed","message-type":"validation-failure","message":[{"type":"unknown-parameter","value":"until-created-date:2018-11-30","message":"Parameter until-created-date:2018-11-30 specified but there is no such parameter available on any route"}]}

However, according to your documentation history, the filter should have existed since Oct. 2015 (v.26).

By the way, is there another way to solely get the articles published in a given month (e.g. "created-date:2018-11")? Or is it always necessary to specify the first date and the last date of a month ("from-created-date" and "until-created-date")?

Thank you!

**Comment by pdavis8** [comment]
Hello,
There was just an ampersand instead of a comma separating the from and until dates.  
https://api.crossref.org/journals/1460-3667/works?sort=issued&order=desc&filter=from-created-date:2018-11-01,until-created-date:2018-11-30
Yes if you are looking for a specific range then you would need to specify a from and until unless it was the last month and you are just running the from-created-date until now affectively.
