### ISSUE TITLE
Journal abbreviations should not appear in container-title

### ISSUE THREAD

**Issue by aurimasv** [CrossRef/rest-api-doc#43]
http://api.crossref.org/works/10.1108/02683940810904367 has both the full and abbreviated journal titles in the `container-title` field
`"container-title":["Journal of Managerial Psych","Journal of Managerial Psychology"]`

http://api.crossref.org/works/10.1021%2Fac010694%2B does the same thing: `"container-title":["Anal. Chem.","Analytical Chemistry"]`

(1) It's not clear if there is any real ordering of titles in container-title field. It seems that the full title is second, but given #19 there is no reliable way to parse this.

(2) While I'm excited that CrossRef JSON responses try to be compatible with Citeproc JSON specification, having arrays for title, container-title, subtitle, etc. goes against the spec. Citeproc JSON requires these to be strings and it does provide several fields (e.g. shorttitle, container-title-short, collection-title, etc.) to spread this metadata out. Though, it seems to me that adhering to Citeproc JSON is not necessarily the best route for this project anyway (based on some other issues that have been raised). In any case, I think that the ambiguity here does call for a better solution.

(3) Abbreviated titles are rather useless as part of the metadata. Different citation styles call for different abbreviations and most of the time these abbreviations can be generated on-the-fly. Additionally, it doesn't seem like the abbreviations are provided consistently via CrossRef API. They're often unavailable or formatted differently (see above two examples and placement of periods after abbreviated words)

**Comment by aurimasv** [comment]
On the topic of incompatibility with Citeproc JSON, neither [`"type":"book-chapter"`](http://api.crossref.org/works/10.1057/9780230391116.0016) nor [`"type":"journal-article"`](http://api.crossref.org/works/10.7554/eLife.05244) are valid. These should be "chapter" and "article-journal", respectively.

**Comment by kjw** [comment]
@aurimasv Thanks for taking the time to look through this. A few comments to avoid confusion:

The default response type of the API is not citeproc JSON. It is a format that is based on citeproc JSON but, as you've noted, differs in some ways that make it incompatible with citeproc tools. For example, differing types, changes to the types of some fields (arrays instead of strings) and also (though this may no longer be an incompatibility) additional fields such as `funder` for funding information, `license` for license information, so on.

Citeproc JSON was a fantastic base for our own format that allows us clearly represent our metadata.

We do provide a more standard citeproc JSON:

    http://api.crossref.org/works/10.1108/02683940810904367/transform/application/vnd.citationstyles.csl+json

This should successfully run through citeproc js. Where it does not, I would want to fix it immediately.

I'm also interested in hearing how anyone thinks our default representation (the one based on citeproc JSON) should change. However, implementation of such changes will be slower - any backwards incompatible changes will have to wait for version bumps on the API.

**Comment by kjw** [comment]
I'm going to look through the points you raise and make sure they are addressed within our citeproc JSON transform. I'll leave this bug to track the progress of that.

**Comment by aurimasv** [comment]
Thanks, Karl, for elaborating on the format. I'm actually glad to hear that you're not scking to Citeproc JSON (I got the impression that you were from all the other bugs that I rread

**Comment by gbilder** [comment]
container-title problems were solved with reindex.
