### ISSUE TITLE
search query does not return AND results

### ISSUE THREAD

**Issue by tautme** [CrossRef/rest-api-doc#461]
README example doesn't return AND but instead returns AND/OR

"Free form search queries can be made, for example, works that include renear and ontologies:"
`https://api.crossref.org/works?query=renear+ontologies
`
https://github.com/CrossRef/rest-api-doc#queries

Is there a work around to search for only DOI's with renear AND ontologies?

RELATED
#170 #447 #461 #401

**Comment by pdavis8** [comment]
At the moment I am afraid the API does not support boolean searches and as such the results will contain all matches that contain either of the search terms. The API should return the titles that contain both words higher in the list based on the scores but it still will return all results.

You can use `query.title` to search just within the title of the record to be more specific. You can also use `query.container-title` to search against the journal or book etc rather than the article or chapter.

By adding words to the search you can refine the results that are returned. The REST API effectively allows you to accomplish this by letting you establish a score threshold beyond which they don’t return results. In the above example, “adding words” to the title effectively boosts the score of the known item DOI . You can simply not show items that fall below whatever score threshold you decide on.
