### ISSUE TITLE
Journal issue publication date being used instead of journal article date

### ISSUE THREAD

**Issue by kjw** [CrossRef/rest-api-doc#69]
Sometimes these differ - for example one may be more granular than the other. When both are provided, it appears journal issue date is used over journal article date.

**Comment by ckoscher** [comment]
article date should take precedence

**Comment by hubgit** [comment]
As an example of where this is causing a problem, one CrossRef API consumer is not able to pull in the full publication date for [an article](https://growkudos.com/articles/10.7717/peerj.1198), as only the journal issue date is being returned as the "issued" date by the API.

I can see that the solution isn't entirely simple, as sometimes the official publication date of an article might be the print date of the journal issue rather than an earlier online publication date, but I'm not sure how common that is and whether there's a way to distinguish between the two situations using the deposited metadata.

**Comment by hubgit** [comment]
I'm using the API to show a list of each journal's latest articles in https://megajournals.info - it would be nice if `sort=published&order=desc` actually showed the most recently published articles for all journals :)

**Comment by hubgit** [comment]
Another case with problematic dates is https://api.crossref.org/works/10.1186/s40064-015-0799-8 - the article's publication date is 2015-01-15 (the "created" date in the API response), while for whatever reason the "issued" date is 2015-12. When sorting by "issued", the most recently published articles are not at the top of the list.

**Comment by kjw** [comment]
Date handling in our solr index has since been overhauled. We now present all known publication dates via the API.

**Comment by hubgit** [comment]
Nice.
