### ISSUE TITLE
Examples of successful click through access

### ISSUE THREAD

**Issue by sckott** [CrossRef/rest-api-doc#75]
I've yet to successfully use the click through API key to get full text from Wiley or Elsevier. 

Anyone have an example that should work?  

Also, are wiley and elsevier checking IP addresses? I assume so. I can VPN via UC berkeley but can't be on campus, so can't really test the IP problem.

**Comment by afandian** [comment]
Elsevier's solution has two steps.

The first part, ensuring that you have agreed to the relevant licenses, can happen either entirely inside their own API or using the click-through service. It's not necessary to use the click-through service if you have agreed to the licenses inside their developer interface, or institutionally. 

The second part, actually retrieving a work involves downloading a resource using a URL (which is considered part of their API), and you must pass their checks to see if you have permission for this. This could involve checking IP addresses, their own tokens or cookies, or something else (I'm not aware of their internals).

What I think is happening in your case is that you have accepted the relevant licenses (i.e. you've chosen to use the click-through for step 1 rather than the Elsevier license acceptance) but the Elsevier API doesn't think that you have the relevant permission.

If you can let us know exactly what request you're making (email labs@crossref.org if it's sensitive) and what response you're getting from the Elsevier server, we can see if we update our documentation or work to improve the usability.

**Comment by sckott** [comment]
Thanks  @afandian for more explanation.  I'll try a bit more, and get in touch if still not working

**Comment by sckott** [comment]
I guess this isn't really Crossref's problem. But it would help to clearly point to documentation on how to figure out how to get access for each publisher, if possible. E.g., i've had a hard time figuring out how to even know if I have access, whether or not I as an individual I have to get access myself, or whether the institution I belong to does that, and who exactly to talk to to make it happen. All this communication is quite slow as well, but again, not your problem.

**Comment by kjw** [comment]
@gbilder Something to think about here?
