### ISSUE TITLE
new 404 errors

### ISSUE THREAD

**Issue by mfenner** [CrossRef/rest-api-doc#77]
Since last week I see random 404 errors leading to a Sinatra 404 page. Not sure yet how to reproduce.

See also https://github.com/lagotto/lagotto/issues/427

**Comment by kjw** [comment]
@ckoscher Since the server move, HTTP requests without a `Host` header are routing by default by haproxy to the backends for search.crossref.org . Really the default should be to route to `api.crossref.org` backends when no `Host` header is provided. It is far more likely `Host`less requests are meant for the API - people will tend to use `search.crossref.org` via a web browser, which all include `Host`.
